[2023-05-20 12:16:09 +0000] [4301] [INFO] Starting gunicorn 20.1.0
[2023-05-20 12:16:09 +0000] [4301] [INFO] Listening at: unix:/var/www/myapp/ipc.sock (4301)
[2023-05-20 12:16:09 +0000] [4301] [INFO] Using worker: sync
[2023-05-20 12:16:09 +0000] [4302] [INFO] Booting worker with pid: 4302
[2023-05-20 12:16:09 +0000] [4303] [INFO] Booting worker with pid: 4303
[2023-05-20 12:16:09 +0000] [4304] [INFO] Booting worker with pid: 4304
[2023-05-25 07:54:02 +0000] [4301] [INFO] Handling signal: term
Traceback (most recent call last):
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 224, in run
[2023-05-25 07:54:02 +0000] [4302] [INFO] Worker exiting (pid: 4302)
[2023-05-25 07:54:02 +0000] [4303] [INFO] Worker exiting (pid: 4303)
[2023-05-25 07:54:02 +0000] [4304] [INFO] Worker exiting (pid: 4304)
    handler()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 257, in handle_term
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/myapp/myenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 227, in run
    self.halt()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 382, in stop
    sock.close_sockets(self.LISTENERS, unlink)
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/sock.py", line 212, in close_sockets
    os.unlink(sock_name)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/myapp/ipc.sock'
[2023-05-25 07:54:03 +0000] [41617] [INFO] Starting gunicorn 20.1.0
[2023-05-25 07:54:03 +0000] [41617] [INFO] Listening at: unix:/var/www/myapp/ipc.sock (41617)
[2023-05-25 07:54:03 +0000] [41617] [INFO] Using worker: sync
[2023-05-25 07:54:03 +0000] [41618] [INFO] Booting worker with pid: 41618
[2023-05-25 07:54:03 +0000] [41619] [INFO] Booting worker with pid: 41619
[2023-05-25 07:54:03 +0000] [41620] [INFO] Booting worker with pid: 41620
[2023-05-25 07:55:19 +0000] [41617] [INFO] Handling signal: term
[2023-05-25 07:55:19 +0000] [41618] [INFO] Worker exiting (pid: 41618)
[2023-05-25 07:55:19 +0000] [41619] [INFO] Worker exiting (pid: 41619)
[2023-05-25 07:55:19 +0000] [41620] [INFO] Worker exiting (pid: 41620)
[2023-05-25 07:55:19 +0000] [41617] [INFO] Shutting down: Master
[2023-05-25 07:55:19 +0000] [41635] [INFO] Starting gunicorn 20.1.0
[2023-05-25 07:55:19 +0000] [41635] [INFO] Listening at: unix:/var/www/myapp/ipc.sock (41635)
[2023-05-25 07:55:19 +0000] [41635] [INFO] Using worker: sync
[2023-05-25 07:55:19 +0000] [41636] [INFO] Booting worker with pid: 41636
[2023-05-25 07:55:20 +0000] [41638] [INFO] Booting worker with pid: 41638
[2023-05-25 07:55:20 +0000] [41637] [INFO] Booting worker with pid: 41637
[2023-05-25 07:59:23 +0000] [41635] [INFO] Handling signal: term
[2023-05-25 07:59:23 +0000] [41636] [INFO] Worker exiting (pid: 41636)
[2023-05-25 07:59:23 +0000] [41637] [INFO] Worker exiting (pid: 41637)
[2023-05-25 07:59:23 +0000] [41638] [INFO] Worker exiting (pid: 41638)
[2023-05-25 07:59:23 +0000] [41635] [INFO] Shutting down: Master
[2023-05-25 07:59:23 +0000] [41656] [INFO] Starting gunicorn 20.1.0
[2023-05-25 07:59:23 +0000] [41656] [INFO] Listening at: unix:/var/www/myapp/ipc.sock (41656)
[2023-05-25 07:59:23 +0000] [41656] [INFO] Using worker: sync
[2023-05-25 07:59:23 +0000] [41657] [INFO] Booting worker with pid: 41657
[2023-05-25 07:59:23 +0000] [41658] [INFO] Booting worker with pid: 41658
[2023-05-25 07:59:23 +0000] [41659] [INFO] Booting worker with pid: 41659
[2023-05-25 08:49:52 +0000] [41656] [INFO] Handling signal: term
Traceback (most recent call last):
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 224, in run
    handler()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 257, in handle_term
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/myapp/myenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 227, in run
    self.halt()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 382, in stop
    sock.close_sockets(self.LISTENERS, unlink)
  File "/var/www/myapp/myenv/lib/python3.10/site-packages/gunicorn/sock.py", line 212, in close_sockets
    os.unlink(sock_name)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/myapp/ipc.sock'
[2023-05-25 08:49:54 +0000] [42794] [INFO] Starting gunicorn 20.1.0
[2023-05-25 08:49:54 +0000] [42794] [INFO] Listening at: unix:/var/www/myapp/ipc.sock (42794)
[2023-05-25 08:49:54 +0000] [42794] [INFO] Using worker: sync
[2023-05-25 08:49:54 +0000] [42799] [INFO] Booting worker with pid: 42799
[2023-05-25 08:49:54 +0000] [42801] [INFO] Booting worker with pid: 42801
[2023-05-25 08:49:55 +0000] [42802] [INFO] Booting worker with pid: 42802
